version: '3.7'
services:
  postgres:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: sale_channel_development
    ports:
      - '5432:5432'
  redis_db:
    image: redis
    ports:
      - '6389:6379'

  spree-store:
    image: spree-store
    build:
      context: .
      args:
        BUNDLE_GITHUB__COM: ${BUNDLE_GITHUB__COM}
    environment:
      DB_HOST: postgres
      REDIS_URL: redis://redis_db:6389/spree-store
      SALE_CHANNEL_TOKEN: 111111
      SALE_CHANNEL_URL: http://sale-channel:5000
    entrypoint: [""]
    command: rails s -p 3000 -b '0.0.0.0' -e production
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis_db

  spree-worker:
    image: spree-store
    entrypoint: [""]
    environment:
      DB_HOST: postgres
      REDIS_URL: redis://redis_db:6389/spree-store
      RAILS_ENV: production
    command: "rake resque:work RAILS_ENV=production QUEUE=*"
    depends_on:
      - postgres
      - redis_db