version: '3.7'
services:
  postgres:
    image: postgres:12.8-alpine
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_DB: sale_channel_development
    ports:
      - '5432:5432'
  redis_db:
    image: redis
    expose:
      - 6379

  spree-store:
    image: spree-store
    build:
      context: .
      args:
        FURY_AUTH: oDJwp-MmpfP9OQAjRbrBnzS9rBEKaZ94M
    environment:
      DB_HOST: postgres
      REDIS_URL: redis://redis_db:6379/1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -e production"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis_db

  spree-worker:
    image: spree-store
    entrypoint: [""]
    environment:
      DB_HOST: postgres
      REDIS_URL: redis://redis_db:6379/1
    command: "rake resque:work RAILS_ENV=production QUEUE=*"
    ports:
      - "8812:8812"
    depends_on:
      - postgres
      - redis_db